import React from 'react';
import {
  Wrench,
  CheckCircle2,
} from 'lucide-react';
import { useSolar } from '../context/SolarContext';

export const MaintenanceSection: React.FC = () => {
  const { maintenanceTasks, updateTaskStatus, cleanPanelArray } = useSolar();

  return (
    <section style={{ marginBottom: '2rem' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '1rem' }}>
        <div>
          <h2 style={{ fontSize: '1.25rem', fontWeight: 700, color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <Wrench size={22} color="var(--green-600)" />
            Section 6 — AI Maintenance Work Orders & Prescriptive Actions
          </h2>
          <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
            Predictive maintenance work orders generated by performance degradation models
          </p>
        </div>

        <div style={{ fontSize: '0.8rem', fontWeight: 700, color: 'var(--green-700)', backgroundColor: 'var(--green-50)', padding: '0.4rem 0.8rem', borderRadius: 'var(--radius-md)', border: '1px solid var(--green-100)' }}>
          Total Gain Potential: +9.3% Output
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '1.25rem' }}>
        {maintenanceTasks.map((task) => {
          const isHigh = task.priority === 'HIGH';
          const isCompleted = task.status === 'COMPLETED';

          return (
            <div
              key={task.id}
              className="card-solid"
              style={{
                padding: '1.25rem',
                opacity: isCompleted ? 0.7 : 1,
                display: 'flex',
                flexDirection: 'column',
                justifyContent: 'space-between',
              }}
            >
              <div>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                  <span className={isHigh ? 'badge-red' : 'badge-yellow'}>
                    Priority: {task.priority}
                  </span>
                  <span style={{ fontSize: '0.7rem', fontWeight: 700, color: 'var(--text-muted)' }}>
                    Target: {task.dueDate}
                  </span>
                </div>

                <h3 style={{ fontSize: '1.05rem', fontWeight: 700, color: 'var(--text-primary)', margin: '0.25rem 0 0.4rem 0' }}>
                  {task.title}
                </h3>

                <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', marginBottom: '1rem', lineHeight: 1.4 }}>
                  {task.description}
                </p>

                {/* Performance Metrics */}
                <div style={{
                  display: 'grid',
                  gridTemplateColumns: '1fr 1fr 1fr',
                  gap: '0.5rem',
                  backgroundColor: 'var(--bg-subtle)',
                  padding: '0.6rem',
                  borderRadius: 'var(--radius-md)',
                  marginBottom: '1rem',
                  fontSize: '0.75rem',
                }}>
                  <div>
                    <div style={{ color: 'var(--text-muted)', fontSize: '0.65rem' }}>Gain Impact</div>
                    <div style={{ fontWeight: 700, color: 'var(--green-600)' }}>+{task.estimatedGainPct}%</div>
                  </div>
                  <div>
                    <div style={{ color: 'var(--text-muted)', fontSize: '0.65rem' }}>Est. Cost</div>
                    <div style={{ fontWeight: 700, color: 'var(--text-primary)' }}>${task.estimatedCostUsd}</div>
                  </div>
                  <div>
                    <div style={{ color: 'var(--text-muted)', fontSize: '0.65rem' }}>Duration</div>
                    <div style={{ fontWeight: 700, color: 'var(--text-primary)' }}>{task.timeRequiredHours} hrs</div>
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: '0.75rem', fontWeight: 700, color: isCompleted ? 'var(--green-600)' : 'var(--text-muted)' }}>
                  Status: {task.status}
                </span>

                {!isCompleted ? (
                  <button
                    onClick={() => {
                      if (task.id === 'MNT-201') cleanPanelArray();
                      updateTaskStatus(task.id, 'COMPLETED');
                    }}
                    className="btn-primary"
                    style={{ fontSize: '0.75rem', padding: '0.35rem 0.75rem' }}
                  >
                    <CheckCircle2 size={14} />
                    <span>Execute Task</span>
                  </button>
                ) : (
                  <span style={{ fontSize: '0.75rem', color: 'var(--green-600)', fontWeight: 700 }}>✓ Verified</span>
                )}
              </div>
            </div>
          );
        })}
      </div>
    </section>
  );
};
